apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:guest
  policy.csv: |
    p, role:guest, applications, get, default/*, allow
    p, role:guest, applications, get, discord-bot/*, allow
    p, role:guest, applications, get, pow/*, allow
    p, role:guest, applications, get, twibot-to-discord/*, allow
    p, role:guest, applications, get, sync/*, allow

    p, role:org-readonly, applications, get, default/*, allow
    p, role:org-readonly, applications, get, pow/*, allow
    p, role:org-readonly, applications, get, twibot-to-discord/*, allow
    p, role:org-readonly, logs, get, *, allow

    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, clusters, create, *, allow
    p, role:org-admin, clusters, upadte, *, allow
    p, role:org-admin, clusters, delete, *, allow
    p, role:org-admin, repositories, get, *, allow
    p, role:org-admin, repositories, create, *, allow
    p, role:org-admin, repositories, update, *, allow
    p, role:org-admin, repositories, delete, *, allow
    p, role:org-admin, projects, get, *, allow
    p, role:org-admin, projects, create, *, allow
    p, role:org-admin, projects, update, *, allow
    p, role:org-admin, projects, delete, *, allow
    p, role:org-admin, logs, get, *, allow
    p, role:org-admin, exec, create, */*, allow

    g, kazu, role:admin
    g, ced, role:org-readonly
