apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  statusbadge.enabled: "true"
  # https://github.com/argoproj/argo-cd/blob/v2.8.4/docs/operator-manual/upgrading/2.3-2.4.md#enable-logs-rbac-enforcement
  # https://github.com/argoproj/argo-cd/issues/10551
  server.rbac.log.enforce.enable: "true"
  users.anonymous.enabled: "true"
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: Ov23liBMMJRLwGZTBy43
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: eoeo-org
  # add an additional local user with apiKey and login capabilities
  #   apiKey - allows generating API keys
  #   login - allows to login using UI
  accounts.kazu: apiKey, login
  accounts.ced: apiKey, login
