apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.8.0
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
          defaultSettings:
            createDefaultDiskLabeledNodes: true
            defaultReplicaCount: 2
            replicaSoftAntiAffinity: false
            replicaAutoBalance: least-effort
            allowVolumeCreationWithDegradedAvailability: false
          networkPolicies:
            enabled: true
            type: "k3s"
          ingress:
            enabled: true
            host: longhorn.mogyuchi.jp
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
