apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.github: ""
  name: oci-secrets
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    path: ""
    repoURL: https://oracle.github.io/oci-secrets-store-csi-driver-provider/charts
    targetRevision: 0.4.1
    chart: oci-secrets-store-csi-driver-provider
    helm:
      parameters:
        - name: secrets-store-csi-driver.syncSecret.enabled
          value: "true"
        - name: secrets-store-csi-driver.enableSecretRotation
          value: "true"
        - name: provider.oci.auth.types.workload.resourcePrincipalRegion
          value: ap-osaka-1
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
