apiVersion: apps/v1
kind: Deployment
metadata:
  name: discordbot-pow-deployment
  labels:
    app: discordbot-pow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discordbot-pow
  template:
    metadata:
      labels:
        app: discordbot-pow
    spec:
      containers:
        - name: discordbot-pow
          image: ghcr.io/j-eoeo/pow:3.8.10@sha256:e5d21397bd24e37f169198cd6d36ad0671744d20f84a66f935ab7dbaaf8dfdcd
          envFrom:
            - secretRef:
                name: pow-token
            - secretRef:
                name: pow-worker-token
            - secretRef:
                name: voicetext
            - secretRef:
                name: pow-db
          securityContext:
            capabilities:
              drop:
                - CAP_MKNOD
                - CAP_NET_RAW
                - CAP_AUDIT_WRITE
          resources:
            requests:
              memory: "130Mi"
              cpu: "15m"
      tolerations:
        - key: "low-spec"
          operator: "Exists"
          effect: "NoExecute"
