apiVersion: apps/v1
kind: Deployment
metadata:
  name: discordbot-pow
  labels:
    app: discordbot-pow
  annotations:
    link.argocd.argoproj.io/external-link: https://github.com/eoeo-org/pow/blob/main/README.md#bot-追加-url
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discordbot-pow
  template:
    metadata:
      labels:
        app: discordbot-pow
    spec:
      containers:
        - name: discordbot-pow
          image: ghcr.io/eoeo-org/pow:3.10.5@sha256:91c2aca7b44628221543501f9a39c3346fe20b5ed7c38c2efddca49172939510
          envFrom:
            - secretRef:
                name: pow-token
            - secretRef:
                name: pow-worker-token
            - secretRef:
                name: voicetext
            - secretRef:
                name: pow-db
          securityContext:
            capabilities:
              drop:
                - CAP_MKNOD
                - CAP_NET_RAW
                - CAP_AUDIT_WRITE
          resources:
            requests:
              memory: "130Mi"
              cpu: "15m"
      tolerations:
        - key: "low-spec"
          operator: "Exists"
          effect: "NoExecute"
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
