apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-eoeo-runners
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: eoeo-runners
    server: https://kubernetes.default.svc
  source:
    chart: gha-runner-scale-set
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.9.3
    helm:
      releaseName: eoeo-runner-set
      parameters:
        - name: githubConfigUrl
          value: "https://github.com/eoeo-org"
        - name: githubConfigSecret
          value: "pre-defined-secret"
  project: gha-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - CreateNamespace=true
      - PruneLast=true
