apiVersion: apps/v1
kind: Deployment
metadata:
  name: pow-summon-bot
  labels:
    app: pow-summon-bot
  annotations:
    link.argocd.argoproj.io/external-link: https://discord.com/oauth2/authorize?client_id=1105143574066122933
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pow-summon-bot
  template:
    metadata:
      labels:
        app: pow-summon-bot
    spec:
      containers:
        - name: pow-summon-bot
          image: ghcr.io/mogyuchi/pow-summon-discordbot:1.0.0@sha256:a85c6ecc7b6fb3e754e8907b9ae0b1dcad74cca11e9c52dbb8ecec7344a65ca3
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: pow-summon-bot-token
          securityContext:
            capabilities:
              drop:
                - CAP_MKNOD
                - CAP_NET_RAW
                - CAP_AUDIT_WRITE
      tolerations:
        - key: "low-spec"
          operator: "Exists"
          effect: "NoExecute"
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
