apiVersion: apps/v1
kind: Deployment
metadata:
  name: om-edge
  labels:
    app: om-edge
  annotations:
    link.argocd.argoproj.io/external-link: https://discord.com/oauth2/authorize?client_id=1245101242443894805
spec:
  replicas: 1
  selector:
    matchLabels:
      app: om-edge
  template:
    metadata:
      labels:
        app: om-edge
    spec:
      containers:
        - name: om-edge
          image: ghcr.io/discordjs-japan/om:edge@sha256:f33db1b61d5ccbb88a3f0c7ba5a3a506fe1fd56496ee79c68f6ffc04957d6b7e
          imagePullPolicy: IfNotPresent # because digest pinning
          envFrom:
            - secretRef:
                name: om-edge-token
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
      tolerations:
        - key: "low-spec"
          operator: "Exists"
          effect: "NoExecute"
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
