apiVersion: apps/v1
kind: Deployment
metadata:
  name: om-edge
  labels:
    app: om-edge
  annotations:
    link.argocd.argoproj.io/external-link: https://discord.com/oauth2/authorize?client_id=1245101242443894805
spec:
  replicas: 1
  selector:
    matchLabels:
      app: om-edge
  template:
    metadata:
      labels:
        app: om-edge
    spec:
      containers:
        - name: om-edge
          image: ghcr.io/discordjs-japan/om:edge@sha256:f7337618fa90f5602e631e997984dcee19c16bc4708b4e4d704e7fae625c1f06
          imagePullPolicy: IfNotPresent # because digest pinning
          envFrom:
            - secretRef:
                name: om-edge-token
          securityContext:
            capabilities:
              drop:
                - CAP_MKNOD
                - CAP_NET_RAW
                - CAP_AUDIT_WRITE
      tolerations:
        - key: "low-spec"
          operator: "Exists"
          effect: "NoExecute"
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
