apiVersion: apps/v1
kind: Deployment
metadata:
  name: ra4nm
  labels:
    app: ra4nm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ra4nm
  template:
    metadata:
      labels:
        app: ra4nm
    spec:
      containers:
        - name: ra4nm
          image: ghcr.io/misskey-art/role-adder-for-new-member:main@sha256:880e351f9e4134b465651f7871d6219aed0a481686412ecf7a8f0571c9f9b430
          imagePullPolicy: Always
          env:
            - name: ROLE_ID
              value: "1074665940270186569"
          envFrom:
            - secretRef:
                name: undefined-token
          securityContext:
            capabilities:
              drop:
                - CAP_MKNOD
                - CAP_NET_RAW
                - CAP_AUDIT_WRITE
      tolerations:
        - key: "low-spec"
          operator: "Exists"
          effect: "NoExecute"
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
