apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mmmm
  namespace: argocd
spec:
  # Project description
  description: ""

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "https://github.com/4m-mazi/k8s-manifests.git"

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  # Destination clusters can be identified by 'server', 'name', or both.
  destinations:
    - namespace: mmmm
      server: https://kubernetes.default.svc
      name: in-cluster

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true
