apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tianji
spec:
  destination:
    name: in-cluster
    namespace: tianji
  source:
    path: ''
    repoURL: https://msgbyte.github.io/charts
    targetRevision: '0.1.17'
    chart: tianji
    helm: 
      parameters:
        - name: image.tag
          value: '1.18.5'
        - name: ingress.enabled
          value: 'true'
        - name: ingress.hosts[0].host
          value: status.mogyuchi.jp
        - name: ingress.hosts[0].paths[0].path
          value: '/'
        - name: ingress.hosts[0].paths[0].pathType
          value: Prefix
        - name: ingress.hosts[1].host
          value: status.misskey.art
        - name: ingress.hosts[1].paths[0].path
          value: '/'
        - name: ingress.hosts[1].paths[0].pathType
          value: Prefix
      values: |
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        affinity:
          nodeaffinity:
            preferredduringschedulingignoredduringexecution:
              - weight: 1
                preference:
                  matchExpressions:
                    - key: topology.kubernetes.io/zone
                      operator: NotIn
                      values:
                        - detda
                        - oracle
  project: tianji
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
