apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tianji
spec:
  destination:
    name: ''
    namespace: tianji
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://msgbyte.github.io/charts
    targetRevision: '0.1.17'
    chart: tianji
    helm: 
      parameters:
        - name: ingress.enabled
          value: 'true'
        - name: ingress.hosts[0].host
          value: status.mogyuchi.jp
        - name: ingress.hosts[0].paths[0].path
          value: '/'
        - name: ingress.hosts[0].paths[0].pathType
          value: Prefix
      values: |
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        tolerations:
          - effect: NoExecute
            key: agent
            operator: Exists
        image:
          tag: "1.17.8"
  project: tianji
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
