apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: buchubot
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: misskey-bots
    server: https://kubernetes.default.svc
  project: misskey-bots
  source:
    path: buchubot
    repoURL: https://github.com/Mogyuchi/k8s-manifests.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
