apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discord-bots
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: discord-bots
    server: https://kubernetes.default.svc
  project: discord-bots
  source:
    path: discord-bots
    repoURL: https://github.com/Mogyuchi/k8s-manifests.git
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
