apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discordbot-pow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: pow
    server: https://kubernetes.default.svc
  project: pow
  source:
    path: pow
    repoURL: https://github.com/Mogyuchi/k8s-manifests.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true