apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: os
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: os
    server: https://kubernetes.default.svc
  project: os
  source:
    path: os
    repoURL: https://github.com/Mogyuchi/k8s-manifests.git
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
