apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smee
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: smee
    server: https://kubernetes.default.svc
  project: smee
  source:
    path: smee
    repoURL: https://github.com/mogyugyu/k8s-deployments.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
