apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: twibot-to-discord
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ced
    server: https://kubernetes.default.svc
  project: twibot-to-discord
  source:
    path: twibot-to-discord
    repoURL: https://github.com/eoeo-org/eoeo-deployments.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
