apiVersion: apps/v1
kind: Deployment
metadata:
  name: buchubot-deployment
  labels:
    app: buchubot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buchubot
  template:
    metadata:
      labels:
        app: buchubot
    spec:
      containers:
        - name: buchubot
          image: ghcr.io/kazukazu123123/buchubot:main@sha256:0d9a2800545513a3517596664b936d714efd1996df06599b4bd68558b0f4a97b
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: buchubot-token
          securityContext:
            capabilities:
              drop:
                - CAP_MKNOD
                - CAP_NET_RAW
                - CAP_AUDIT_WRITE
      tolerations:
        - key: "low-spec"
          operator: "Exists"
          effect: "NoExecute"
