apiVersion: apps/v1
kind: Deployment
metadata:
  name: buchubot-deployment
  labels:
    app: buchubot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buchubot
  template:
    metadata:
      labels:
        app: buchubot
    spec:
      containers:
        - name: buchubot
          image: ghcr.io/kazukazu123123/buchubot:main@sha256:d31faa57ffef56b5ea0a56ae0b719c059465e7cc8c77514c64ac44a975897248
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: buchubot-token
          securityContext:
            capabilities:
              drop:
                - CAP_MKNOD
                - CAP_NET_RAW
                - CAP_AUDIT_WRITE
      tolerations:
        - key: "low-spec"
          operator: "Exists"
          effect: "NoExecute"
