apiVersion: apps/v1
kind: Deployment
metadata:
  name: buchubot
  labels:
    app: buchubot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buchubot
  template:
    metadata:
      labels:
        app: buchubot
    spec:
      containers:
        - name: buchubot
          image: ghcr.io/kazukazu123123/buchubot:main@sha256:cae50f1c4eaa67ec9f58c0ad583243d382bc7c7a0cf36a1daaf65f018c9ef922
          imagePullPolicy: IfNotPresent # because digest pinning
          envFrom:
            - secretRef:
                name: buchubot-token
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
      tolerations:
        - key: "low-spec"
          operator: "Exists"
          effect: "NoExecute"
