apiVersion: apps/v1
kind: Deployment
metadata:
  name: buchubot
  labels:
    app: buchubot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buchubot
  template:
    metadata:
      labels:
        app: buchubot
    spec:
      containers:
        - name: buchubot
          image: ghcr.io/kazukazu123123/buchubot:main@sha256:4307ebac5feb55d9b98f20972dd4d2263673e888c3105eadce5efe4631a7dc2e
          imagePullPolicy: IfNotPresent # because digest pinning
          envFrom:
            - secretRef:
                name: buchubot-token
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
      tolerations:
        - key: "low-spec"
          operator: "Exists"
          effect: "NoExecute"
