apiVersion: apps/v1
kind: Deployment
metadata:
  name: buchubot-deployment
  labels:
    app: buchubot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buchubot
  template:
    metadata:
      labels:
        app: buchubot
    spec:
      containers:
        - name: buchubot
          image: ghcr.io/kazukazu123123/buchubot:main@sha256:a089aa6e6f6b150ef60c0d550c16b395f2e50745a140bae049192c872c0a6379
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: buchubot-token
          securityContext:
            capabilities:
              drop:
                - CAP_MKNOD
                - CAP_NET_RAW
                - CAP_AUDIT_WRITE
      tolerations:
        - key: "low-spec"
          operator: "Exists"
          effect: "NoExecute"
