apiVersion: apps/v1
kind: Deployment
metadata:
  name: buchubot-deployment
  labels:
    app: buchubot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buchubot
  template:
    metadata:
      labels:
        app: buchubot
    spec:
      containers:
        - name: buchubot
          image: ghcr.io/kazukazu123123/buchubot:main@sha256:5f6a8782efe57d7c0a3944fd01743335fa41aec3e501837d14bea137c7fe2730
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: buchubot-token
          securityContext:
            capabilities:
              drop:
                - CAP_MKNOD
                - CAP_NET_RAW
                - CAP_AUDIT_WRITE
