apiVersion: apps/v1
kind: Deployment
metadata:
  name: buchubot-deployment
  labels:
    app: buchubot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buchubot
  template:
    metadata:
      labels:
        app: buchubot
    spec:
      containers:
        - name: buchubot
          image: ghcr.io/kazukazu123123/buchubot:main@sha256:fa201353736a01261d72826dc8c111ed3d387e318970f41e95508926313132be
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: buchubot-token
          securityContext:
            capabilities:
              drop:
                - CAP_MKNOD
                - CAP_NET_RAW
                - CAP_AUDIT_WRITE
      tolerations:
        - key: "low-spec"
          operator: "Exists"
          effect: "NoExecute"
