apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-projects
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: sync
  source:
    path: _projects
    repoURL: https://github.com/Mogyuchi/k8s-manifests.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
